# fly.toml file generated for git-dunxen-dev on 2023-03-31T23:37:50+02:00

app = "git-dunxen-dev"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "jnb"

[env]
  SOFT_SERVE_INITIAL_ADMIN_KEYS = "$SOFT_SERVE_INITIAL_ADMIN_KEYS"
  SOFT_SERVE_SSH_KEY_PATH = "/soft-serve/ssh/soft_serve_server_ed25519"
  SOFT_SERVE_DATA_PATH = "/soft-serve"
  SOFT_SERVE_NAME = "dunxen's 🍦"
  SOFT_SERVE_SSH_PUBLIC_URL = "ssh://git.dunxen.dev:22"
  SOFT_SERVE_GIT_MAX_CONNECTIONS = "20"
  SOFT_SERVE_SSH_IDLE_TIMEOUT = "120"

[mounts]
  source = "data"
  destination = "/soft-serve"

[[services]]
  protocol = "tcp"
  internal_port = 23231
  processes = ["app"]
  [[services.ports]]
    port = 22
  [services.concurrency]
    type = "connections"
    hard_limit = 20
    soft_limit = 20
